| Name | ID | Department |
| --- | --- | --- |
|Abdelrhman Mohamed Abdelhady Hodib| 2022513643 | Intelligent systems|

In [1]:
import numpy as np
#Create a 1-dimensional NumPy array of length 7 with random integers between 0 and 20.
x= np.random.randint(0,20,7)
print(x)
#Insert the value 100 at the third index of the array.
x=np.insert(x, 2, 100)
print(x)
#Then, delete the value at the fifth index of the array.
x=np.delete(x, 4)
print(x)
#Finally, calculate and print the minimum value and the unique valuesof the updated array.
unique=np.unique(x)
print(unique)
minimum=np.min(x) 
print(minimum)


[18  7 13 17 16 19  8]
[ 18   7 100  13  17  16  19   8]
[ 18   7 100  13  16  19   8]
[  7   8  13  16  18  19 100]
7


In [2]:
# Create a 2D numpy array with dimensions (3,4) and fill it with random integers between1 and 10
xy = np.array([[5,5,5,5],[4,3,3,3],[0,2,8,6]])
x0=np.array([[0,0,0,0], [0,0,0,0],[0,0,0,0]]) 
# Then, append a row of zeros at the end of the array, and reshape the array to(4,4).
X3 =np.append(xy,x0,axis=0)
#Finally, find the maximum value in the array.
maxvalue=np.max(X3) 
print(maxvalue)

8


In [3]:
#Create a 2D numpy array with dimensions (4,5) and fill it with random integers between1 and 100
arr= np.random.randint(100, size=(4, 5)) 

#Then, insert a column of ones at index 2, and delete the first row of the array.
arr=np.insert(arr,1,[1,1,1,1,1])
print(arr)
arr = np.delete(arr, 0, 0)  
print("The array after Deletion:",arr)
#Finally, compute the mean of the remaining elements in the array.
mean = np.mean(arr) 
print("The mean of the array:",mean)

[95  1  1  1  1  1 56 24 85 86 80 58 76 68 76 57  2 92 48 30 41 28 45 83
 27]
The array after Deletion: [ 1  1  1  1  1 56 24 85 86 80 58 76 68 76 57  2 92 48 30 41 28 45 83 27]
The mean of the array: 44.458333333333336


In [5]:
#Create a 3D numpy array of shape (2, 3, 4) filled with ones. 
array= np.full(
  shape=(2,3,4),
  fill_value=1,
  dtype=np.int
)
print(array)
#Then, use the delete function to delete the second row of the second dimension
array = np.delete(array, 1,1)
print("The array After deletion:\n",array)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
The array After deletion:
 [[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


C:\Users\KIMO STORE\AppData\Local\Temp\ipykernel_6188\3196405470.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int


In [8]:
#Create a 3-dimensional numpy array with shape (2, 3, 4) and fill it with random numbersbetween 0 and 1
array= np.random.randint(2, size=(2,3, 4))
print(array)
#Then, reshape it into a 2-dimensional array with shape (6, 4).
arr2 = np.reshape(array, (6, 4))
print("The array After Reshaping:\n",arr2)

[[[1 1 1 1]
  [1 0 1 1]
  [0 0 0 1]]

 [[1 0 1 0]
  [1 0 0 1]
  [1 0 0 1]]]
The array After Reshaping:
 [[1 1 1 1]
 [1 0 1 1]
 [0 0 0 1]
 [1 0 1 0]
 [1 0 0 1]
 [1 0 0 1]]
